version: '3.8'

services:
  crud-postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db_crud
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data